DELETE http://localhost:3003/api/blogs/60c78ddd5b235e2374231255
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hc2EiLCJpZCI6IjYwYzVlMWE0OWExNWRlMmU4YzA1YTliZCIsImlhdCI6MTYyMzU4NTA4N30.rwTSoZJvc5TJ49HV9xNARXoHS2S5SwgQU-3Vdsoj8SA

###

DELETE http://localhost:3003/api/blogs/60c78ddd5b235e2374231255
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlbmFhdHRvcmkiLCJpZCI6IjYwYzhlOTE3YWFlOTUxMzA1MGU2Y2M2NSIsImlhdCI6MTYyMzc3OTc3NX0.fHhP82UjGhEq0DuSP6BMfax-9aRsXEA0bOtuTVKgS9Y