POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Masa",
    "password": "mattionparas"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Penaattori",
    "password": "salasana"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Masa",
    "password": "mattionparaZ"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "MaZa",
    "password": "mattionparas"
}